name: Deploy Python project to Azure Function App

on:
  push:
    branches: ["master"]

env:
  AZURE_FUNCTIONAPP_NAME: 'your-app-name'   # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'       # set this to the path to your function app project, defaults to the repository root
  PYTHON_VERSION: '3.9'                     # set this to the python version to use (e.g. '3.6', '3.7', '3.8')

jobs:
  build-and-archive:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Resolve Project Dependencies Using Pip'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        popd
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: function-code
        path: ./

  tag-release:
    needs: build-and-archive
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install semantic-release
        run: |
          npm install -g semantic-release @semantic-release/git conventional-changelog-conventionalcommits
      - name: Run Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#  release-dev:
#    runs-on: ubuntu-latest
#    environment: dev
#    steps:
#      - name: 'Checkout GitHub Action'
#        uses: actions/checkout@v3
#      - name: 'Run Azure Functions Action'
#        uses: Azure/functions-action@v1
#        id: fa
#        with:
#          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
#          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
#          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }} # Remove publish-profile to use Azure RBAC
#          scm-do-build-during-deployment: true
#          enable-oryx-build: true